
# update
- hosts: all
  tasks:
    - name: install basic packages
      apt: name={{ item }} update_cache=yes state=latest
      with_items:
        - git
        - build-essential
        - python
        - python-dev
        - nasm
        - iasl
        - clang
        - uuid-dev
        - libssl-dev
      become: true

    # Toolchain
    - name: install cross-compiler for aarch64
      unarchive:
        src: https://releases.linaro.org/components/toolchain/binaries/latest/aarch64-linux-gnu/gcc-linaro-7.2.1-2017.11-x86_64_aarch64-linux-gnu.tar.xz
        dest: /usr/local/
        remote_src: True
      become: true
    - name: install cross-compiler for aarch32(hf)
      unarchive:
        src: https://releases.linaro.org/components/toolchain/binaries/latest/arm-linux-gnueabihf/gcc-linaro-7.2.1-2017.11-x86_64_arm-linux-gnueabihf.tar.xz
        dest: /usr/local/
        remote_src: True
      become: true

    # EDK2
    - name: clone edk2
      git:
        repo: https://github.com/tianocore/edk2
        dest: ~/edk2
        force: yes
        version: master
        depth: 1
    - name: Enable HTTP boot for ArmVirtQemu
      replace:
        regexp: " *DEFINE *HTTP_BOOT_ENABLE *= *FALSE"
        replace: " DEFINE HTTP_BOOT_ENABLE = TRUE"
        path: ~/edk2/ArmVirtPkg/ArmVirtQemu.dsc
    - name: uefi-tools helper scripts
      git:
        repo: https://git.linaro.org/uefi/uefi-tools.git
        dest: ~/uefi-tools
        version: master
        depth: 1
    - name: Build OVMF image for qemu-aarch64
      command: "~/uefi-tools/uefi-build.sh qemu64"
      args:
        chdir: "~/edk2"
      environment:
        GCC5_AARCH64_PREFIX: "aarch64-linux-gnu-"
        PATH: "{{ ansible_env.PATH }}:/usr/local/gcc-linaro-7.2.1-2017.11-x86_64_aarch64-linux-gnu/bin"
    - name: fetch QEMU_EFI.fd
      fetch:
        src: "~/edk2/Build/ArmVirtQemu-AARCH64/RELEASE_GCC5/FV/QEMU_EFI.fd"
        dest: "fetched_files"


    # build hikey UEFI image
    - name: create workspace for hikey
      file:
        path: ~/hikey-uefi/
        state: directory
    - name: clone uefi-tools to workspace
      git:
        repo: https://git.linaro.org/uefi/uefi-tools
        dest: ~/hikey-uefi/uefi-tools
        version: master
        depth: 1
        force: yes
    - name: Replace BUILDFLAGS if hardware is built by CircuitCo
      replace:
        regexp: "#BUILDFLAGS=-DSERIAL_BASE=0xF8015000"
        replace: "BUILDFLAGS=-DSERIAL_BASE=0xF8015000"
        path: ~/hikey-uefi/uefi-tools/platforms.config
    - name: clone arm-trusted-firmware to workspace
      git:
        repo: https://github.com/ARM-software/arm-trusted-firmware
        dest: ~/hikey-uefi/arm-trusted-firmware
        version: integration
        depth: 1
    - name: clone optee_os to workspace
      git:
        repo: https://github.com/OP-TEE/optee_os
        dest: ~/hikey-uefi/optee_os
        version: master
        depth: 1
    - name: clone edk2 to workspace
      git:
        repo: https://github.com/96boards-hikey/edk2
        dest: ~/hikey-uefi/edk2
        version: testing/hikey960_v2.5
        depth: 1
    - name: clone OpenPlatformPkg to workspace
      git:
        repo: https://github.com/96boards-hikey/OpenPlatformPkg
        dest: ~/hikey-uefi/OpenPlatformPkg
        version: testing/hikey960_v1.3.4
        depth: 1
        force: yes
    - name: Create symbolic link to edk2
      file:
        src: ~/hikey-uefi/OpenPlatformPkg
        dest: ~/hikey-uefi/edk2/OpenPlatformPkg
        state: link
    - name: appply patch for enable http boot
      patch:
        src: files/Hikey.dsc.patch
        dest: ~/hikey-uefi/OpenPlatformPkg/Platforms/Hisilicon/HiKey/HiKey.dsc
        binary: yes
    - name: clone l-loader to workspace
      git:
        repo: https://github.com/96boards-hikey/l-loader
        dest: ~/hikey-uefi/l-loader
        version: testing/hikey960_v1.2
        depth: 1
    - name: clone atf-fastboot to workspace
      git:
        repo: https://github.com/96boards-hikey/atf-fastboot
        dest: ~/hikey-uefi/atf-fastboot
        version: master
        depth: 1

    # build fastboot
    - name: Build atf-fastboot for hikey
      command: "make -j2 PLAT=hikey DEBUG=1"
      args:
        chdir: "~/hikey-uefi/atf-fastboot"
      environment:
        AARCH64_TOOLCHAIN: "GCC5"
        CROSS_COMPILE: "aarch64-linux-gnu-"
        EDK2_DIR: "~/hikey-uefi/edk2"
        BUILD_OPTION: "DEBUG"
        PATH: "{{ ansible_env.PATH }}:/usr/local/gcc-linaro-7.2.1-2017.11-x86_64_aarch64-linux-gnu/bin:/usr/local/gcc-linaro-7.2.1-2017.11-x86_64_arm-linux-gnueabihf/bin"
    # build edk2
    - name: Build uefi image for hikey
      command: "~/hikey-uefi/uefi-tools/uefi-build.sh -b DEBUG -a ~/hikey-uefi/arm-trusted-firmware -s ~/hikey-uefi/optee_os hikey"
      args:
        chdir: "~/hikey-uefi/edk2"
      environment:
        AARCH64_TOOLCHAIN: "GCC5"
        CROSS_COMPILE: "aarch64-linux-gnu-"
        EDK2_DIR: "~/hikey-uefi/edk2"
        PATH: "{{ ansible_env.PATH }}:/usr/local/gcc-linaro-7.2.1-2017.11-x86_64_aarch64-linux-gnu/bin:/usr/local/gcc-linaro-7.2.1-2017.11-x86_64_arm-linux-gnueabihf/bin"
    # build l-loader
    - name: create bl1 symbolic link for l-loader
      file:
        src: ~/hikey-uefi/edk2/Build/HiKey/DEBUG_GCC5/FV/bl1.bin
        dest: ~/hikey-uefi/l-loader/bl1.bin
        state: link
    - name: create fastboot symbolic link for l-loader
      file:
        src: ~/hikey-uefi/atf-fastboot/build/hikey/debug/bl1.bin
        dest: ~/hikey-uefi/l-loader/fastboot.bin
        state: link
    - name: Build l-loader for hikey
      command: "make hikey PTABLE_LST=linux-4g"
      args:
        chdir: "~/hikey-uefi/l-loader"
      environment:
        PATH: "{{ ansible_env.PATH }}:/usr/local/gcc-linaro-7.2.1-2017.11-x86_64_aarch64-linux-gnu/bin:/usr/local/gcc-linaro-7.2.1-2017.11-x86_64_arm-linux-gnueabihf/bin"
    - name: fetch files for hikey
      fetch:
        src: ~/hikey-uefi/l-loader/{{ item }}
        dest: "fetched_files/"
        flat: yes
      with_items:
        - l-loader.bin
        - ptable-linux-4g.img
        - fastboot.bin